# -*- coding: utf-8 -*-
"""HealthPulseAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aX08GVTGj3trFxtY6Dc2hbCha-bKjrjj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import joblib
import os

# Helper to clean column names
def clean_cols(df):
    df.columns = [c.lower().replace(' ', '_').strip() for c in df.columns]
    return df

# Step 1: Data Loading & Cleaning
files = [
    'AyurGenixAI_Dataset.csv', 'ayurveda_dataset.csv', 'MedLeafRec_Dataset.csv',
    'Updated_Prakriti_With_Features.csv', 'healthcare_disease_prediction_2000.csv',
    'disease_diagnosis.csv', 'Final_Augmented_dataset_Diseases_and_Symptoms-selected-columns.csv',
    'Testing-selected-columns.csv'
]

dataframes = {}
for f in files:
    path = f'/content/{f}'
    if os.path.exists(path):
        df = pd.read_csv(path)
        dataframes[f] = clean_cols(df)

# Standardize disease names in key files for merging
for df_key in dataframes:
    for col in ['disease', 'diagnosed_disease', 'label', 'prognosis']:
        if col in dataframes[df_key].columns:
            dataframes[df_key][col] = dataframes[df_key][col].astype(str).str.lower().str.strip()

# Step 2: Data Processing & ETL (Fusion)
# Combine symptoms in disease_diagnosis.csv
diag_df = dataframes['disease_diagnosis.csv']
symptom_cols = [c for c in diag_df.columns if 'symptom' in c]
diag_df['combined_symptoms'] = diag_df[symptom_cols].apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)

# Inspect columns to find the disease label
# Common candidates after cleaning are 'disease', 'diagnosed_disease', 'label', 'prognosis'
diag_disease_col = None
possible_cols = ['disease', 'diagnosed_disease', 'label', 'prognosis']
for col in possible_cols:
    if col in diag_df.columns:
        diag_disease_col = col
        break

if diag_disease_col is None:
    # Fallback to the last column if typical names aren't found
    diag_disease_col = diag_df.columns[-1]

# Merge clinical records with Ayurvedic datasets
ayur_df = pd.concat([dataframes['AyurGenixAI_Dataset.csv'], dataframes['ayurveda_dataset.csv']], ignore_index=True, sort=False)
ayur_disease_col = 'disease' if 'disease' in ayur_df.columns else ('problem' if 'problem' in ayur_df.columns else ayur_df.columns[0])

# Create unified merged data
merged_data = pd.merge(diag_df, ayur_df, left_on=diag_disease_col, right_on=ayur_disease_col, how='left')

# Ensure 'disease' column exists for subsequent steps
merged_data['disease'] = merged_data[diag_disease_col]

# Handle missing values
if 'age' in merged_data.columns:
    merged_data['age'] = pd.to_numeric(merged_data['age'], errors='coerce').fillna(merged_data['age'].median())
if 'gender' in merged_data.columns:
    merged_data['gender'] = merged_data['gender'].fillna('Unknown')

print(f"Using '{diag_disease_col}' from diagnosis file and '{ayur_disease_col}' from Ayurvedic file.")
print("Merged Data columns:", merged_data.columns.tolist())
display(merged_data.head())

# Step 3: Exploratory Data Analysis (EDA)
import matplotlib.pyplot as plt
import seaborn as sns

if 'merged_data' in locals():
    plt.figure(figsize=(12, 6))
    # Check for 'disease' column and plot
    plot_col = 'disease' if 'disease' in merged_data.columns else (merged_data.select_dtypes(include=['object']).columns[0] if not merged_data.select_dtypes(include=['object']).columns.empty else None)

    if plot_col:
        sns.countplot(data=merged_data, x=plot_col, hue='gender' if 'gender' in merged_data.columns else None)
        plt.title(f'Diagnosis Counts: {plot_col} by Gender')
        plt.xticks(rotation=90)
        plt.tight_layout()
        plt.savefig('disease_gender_dist.png')
        plt.show()

    # Vitals Correlation Matrix
    vital_cols = [c for c in ['blood_pressure', 'temperature', 'heart_rate', 'glucose', 'age'] if c in merged_data.columns]
    if len(vital_cols) > 1:
        plt.figure(figsize=(10, 8))
        sns.heatmap(merged_data[vital_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
        plt.title('Feature Correlation Matrix for Numerical Vitals')
        plt.savefig('vitals_correlation.png')
        plt.show()
else:
    print('merged_data not found. Please run Step 2 first.')

# Step 4: Machine Learning Model Training & Evaluation
from sklearn.preprocessing import LabelEncoder
from scipy.sparse import hstack
import joblib

if 'merged_data' in locals():
    # Vectorize symptom text
    tfidf = TfidfVectorizer(max_features=2000, stop_words='english')
    text_col = 'combined_symptoms' if 'combined_symptoms' in merged_data.columns else 'symptom_1'
    X_text = tfidf.fit_transform(merged_data[text_col].fillna(''))

    # Handle renamed columns after merge (gender_x, gender_y, etc.)
    gender_col = 'gender_x' if 'gender_x' in merged_data.columns else ('gender' if 'gender' in merged_data.columns else None)

    if gender_col:
        merged_data[gender_col] = merged_data[gender_col].astype(str)
        le_gender = LabelEncoder()
        merged_data['gender_enc'] = le_gender.fit_transform(merged_data[gender_col])
    else:
        merged_data['gender_enc'] = 0

    # Prepare features: Age and Gender
    # Ensure age is numeric
    merged_data['age'] = pd.to_numeric(merged_data['age'], errors='coerce').fillna(0)
    X_num = merged_data[['age', 'gender_enc']].values

    # Combine features
    X = hstack([X_text, X_num])
    y = merged_data['disease'].fillna('unknown')

    # Split data - handling case with single class for stratification
    counts = y.value_counts()
    stratify_target = y if (counts > 1).all() and len(counts) > 1 else None

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=stratify_target)

    # Train Model
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Evaluation
    y_pred = model.predict(X_test)
    print(f'Accuracy Score: {accuracy_score(y_test, y_pred):.4f}')
    print('\nClassification Report:\n', classification_report(y_test, y_pred, zero_division=0))

    # Export artifacts
    joblib.dump(model, 'ayurvedic_disease_model.pkl')
    joblib.dump(tfidf, 'symptom_tfidf_vectorizer.pkl')
    print('Model and Vectorizer exported as .pkl files.')
else:
    print('merged_data not found.')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score
import joblib

# ==========================================
# STEP 1: DATA LOADING & CLEANING
# ==========================================
print("=== STEP 1: CLEANING DATASETS ===")

# Load datasets
df_ayur_genix = pd.read_csv('AyurGenixAI_Dataset.csv')
df_ayurveda = pd.read_csv('ayurveda_dataset.csv')
df_medleaf = pd.read_csv('MedLeafRec_Dataset.csv')
df_prakriti = pd.read_csv('Updated_Prakriti_With_Features.csv')
df_health_pred = pd.read_csv('healthcare_disease_prediction_2000.csv')
df_disease_diag = pd.read_csv('disease_diagnosis.csv')
df_symptoms = pd.read_csv('Final_Augmented_dataset_Diseases_and_Symptoms-selected-columns.csv')

# Standardize column names across all DataFrames
for df in [df_ayur_genix, df_ayurveda, df_medleaf, df_prakriti, df_health_pred, df_disease_diag, df_symptoms]:
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('&', 'and')

# Clean disease diagnosis table
df_disease_diag.drop_duplicates(subset=['patient_id'], inplace=True)
df_disease_diag['symptoms_combined'] = df_disease_diag[['symptom_1', 'symptom_2', 'symptom_3']].fillna('').agg(' '.join, axis=1)

# Clean string columns for joining
df_ayur_genix.dropna(subset=['disease', 'symptoms'], inplace=True)
df_ayur_genix['disease_clean'] = df_ayur_genix['disease'].str.strip().str.lower()
df_disease_diag['diagnosis_clean'] = df_disease_diag['diagnosis'].str.strip().str.lower()

print("✓ Datasets cleaned and normalized.")


# ==========================================
# STEP 2: DATA PROCESSING & ETL (FUSION)
# ==========================================
print("\n=== STEP 2: DATA PROCESSING & ETL ===")

# Merge clinical patient diagnoses with Ayurvedic remedy data
df_integrated = pd.merge(
    df_disease_diag,
    df_ayur_genix[['disease_clean', 'doshas', 'ayurvedic_herbs', 'formulation', 'diet_and_lifestyle_recommendations']],
    left_on='diagnosis_clean',
    right_on='disease_clean',
    how='inner'
)

print(f"✓ Integrated dataset built successfully ({df_integrated.shape[0]} patient-remedy mappings created).")
print(df_integrated[['patient_id', 'age', 'gender', 'diagnosis', 'doshas', 'ayurvedic_herbs']].head())


# ==========================================
# STEP 3: EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================
print("\n=== STEP 3: EXPLORATORY DATA ANALYSIS ===")

sns.set_theme(style="whitegrid")

# Plot 1: Disease breakdown by Gender
plt.figure(figsize=(10, 4))
sns.countplot(data=df_disease_diag, x='diagnosis', hue='gender')
plt.title('Disease Breakdown by Gender')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('disease_by_gender.png')
plt.show()

# Plot 2: Top Imbalanced Doshas
if not df_integrated.empty:
    plt.figure(figsize=(8, 4))
    df_integrated['doshas'].value_counts().head(10).plot(kind='bar', color='teal')
    plt.title('Top Imbalanced Doshas across Diagnoses')
    plt.ylabel('Count')
    plt.tight_layout()
    plt.savefig('dosha_distribution.png')
    plt.show()


# ==========================================
# STEP 4: MODEL TRAINING & EVALUATION
# ==========================================
print("\n=== STEP 4: MODEL TRAINING ===")

# Feature engineering: TF-IDF on symptoms + Numerical Demographics (Age, Gender)
tfidf = TfidfVectorizer(max_features=100)
X_symptoms = tfidf.fit_transform(df_disease_diag['symptoms_combined']).toarray()

df_disease_diag['gender_num'] = df_disease_diag['gender'].map({'Male': 0, 'Female': 1}).fillna(0)
X = np.hstack((X_symptoms, df_disease_diag[['age', 'gender_num']].values))
y = df_disease_diag['diagnosis']

# Stratified Train-Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Train Classifier
model_disease = RandomForestClassifier(n_estimators=100, random_state=42)
model_disease.fit(X_train, y_train)

# Evaluate
y_pred = model_disease.predict(X_test)
print(f"Model Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Export models
joblib.dump(model_disease, 'disease_predictor_model.pkl')
joblib.dump(tfidf, 'symptom_vectorizer.pkl')
print("✓ Trained model and vectorizer saved as .pkl files.")

import pandas as pd
import joblib

# 1. Load the CSV file into a DataFrame
df = pd.read_csv('AyurGenixAI_Dataset.csv')

# 2. Save/serialize the DataFrame directly to a .pkl file
joblib.dump(df, 'AyurGenixAI_Dataset.pkl')

print("✓ Successfully converted AyurGenixAI_Dataset.csv to AyurGenixAI_Dataset.pkl")

import pandas as pd
import joblib

# Load the dataframe directly from pickle
ayurveda_df = joblib.load('AyurGenixAI_Dataset.pkl')